import type { Locale } from "@/lib/locale";

// UI copy for /research (and the shared LoginForm). User-authored content —
// project names, artifact titles, the artifact HTML — is shown as written.
// `en` is typed as `ResearchCopy`, so a missing key is a compile error.

const ja = {
  common: {
    save: "保存",
    cancel: "キャンセル",
    close: "閉じる",
    closeX: "閉じる ✕",
    delete: "削除",
    confirmDelete: "本当に削除する",
    copy: "コピー",
    copied: "コピーしました",
    required: "必須",
    loading: "読み込み中…",
    descriptionOptional: "説明（任意）",
    description: "説明",
    title: "タイトル",
  },
  visibility: {
    label: "公開範囲",
    publicTitle: "誰でも閲覧可（ログイン不要・検索対象）",
    membersTitle: "メンバーのみ閲覧可",
    membersOption: "メンバーのみ",
    publicOption: "誰でも（検索にも載る）",
    makePublic: "誰でも公開にする",
    makeMembers: "メンバー限定に戻す",
    changeFailed: "公開範囲の変更に失敗しました。",
  },
  header: {
    projects: "プロジェクト",
    settings: "設定",
    members: "メンバー",
    logout: "ログアウト",
    menu: "メニュー",
  },
  index: {
    title: "プロジェクト",
    lead: "Claude が作った HTML アーティファクトをプロジェクト単位で整理します。Cowork / Claude からの公開先は「設定」で確認できます。",
    empty: "まだプロジェクトがありません。「新規プロジェクト」から作成してください。",
    count: (n: number) => `${n} 件`,
    updated: (date: string) => `更新 ${date}`,
  },
  publicIndex: {
    title: "Research",
    lead: "Bakerization が調査・分析したレポートを公開しています。パン屋と食、テクノロジーにまつわるリサーチを、プロジェクトごとにまとめています。",
    projects: "プロジェクト",
    latest: "最新のリサーチ",
    empty: "公開中のリサーチはまだありません。",
    reports: (n: number) => `${n} 件のリサーチ`,
    updated: (date: string) => `更新 ${date}`,
    open: "読む →",
  },
  publicProject: {
    back: "← Research 一覧",
    reports: (n: number) => `${n} 件のリサーチ`,
  },
  newProject: {
    open: "＋ 新規プロジェクト",
    name: "プロジェクト名",
    creating: "作成中…",
    create: "作成する →",
    failed: "作成に失敗しました。",
  },
  board: {
    viewToggle: "表示切替",
    list: "リスト",
    grid: "グリッド",
    projectSettings: "プロジェクト設定",
    upload: "＋ アップロード",
    name: "プロジェクト名",
    deleteProject: "プロジェクトを削除",
    confirmDeleteProject: "本当に削除する（中身は Inbox へ）",
    empty: "アーティファクトはまだありません。「アップロード」、または Claude（MCP コネクタ）/ API から追加してください。",
    dragHint: "⋮⋮ をドラッグして並び替え（キーボード: ハンドルにフォーカス → Space → 矢印 → Space）",
    colPreview: "プレビュー",
    colMeta: "タイトル · ソース · 作成者 · 更新日",
    colActions: "操作",
    reorderFailed: "並び替えの保存に失敗しました。元の順序に戻しました。",
    updateFailed: "プロジェクトの更新に失敗しました。",
    deleteFailed: "プロジェクトの削除に失敗しました。",
  },
  item: {
    dragHandle: "並び替え（ドラッグ、または Space → 矢印キー → Space）",
    open: "開く",
    rename: "名前変更",
    move: "移動",
    moveTo: "移動先を選択…",
    updateFailed: "更新に失敗しました。",
    moveFailed: "移動に失敗しました。",
    deleteFailed: "削除に失敗しました。",
  },
  upload: {
    title: "HTMLをアップロード",
    onlyHtml: ".html ファイルのみ対応しています。",
    tooLarge: (limit: string) => `ファイルが大きすぎます（上限 ${limit}）。`,
    empty: "HTMLが空です。",
    failed: "アップロードに失敗しました。",
    selected: (name: string) => `選択中: ${name}`,
    drop: "ファイルを選択、またはここにドロップ（.html）",
    paste: "またはHTMLを貼り付け",
    uploading: "アップロード中…",
    submit: "アップロード →",
  },
  viewer: {
    backTo: (name: string) => `${name} に戻る`,
    backHome: "Research 一覧へ",
    descriptionPlaceholder: "説明を追加…",
    details: "詳細と操作",
    rename: "名前変更",
    openHtml: "HTMLを開く ↗",
    download: "ダウンロード",
    copyUrl: "URLをコピー",
    saveFailed: "保存に失敗しました。",
    deleteFailed: "削除に失敗しました。",
  },
  settings: {
    title: "設定",
  },
  apiKeys: {
    lead: "REST API（curl / Claude Code のスクリプト）用のキーです。発行時に一度だけ表示されます。",
    fetchFailed: "キーの取得に失敗しました。",
    createFailed: "キーの発行に失敗しました。",
    revokeFailed: "失効に失敗しました。",
    revealWarning: "▲ このキーは今回しか表示されません。今すぐコピーして安全な場所に保存してください。",
    name: "キーの名前（例: Claude Code / 自動化スクリプト）",
    issue: "発行する →",
    none: "キーはまだありません。",
    created: (date: string) => `作成 ${date}`,
    lastUsed: (date: string) => `最終使用 ${date}`,
    unused: "未使用",
    revoke: "失効",
    confirmRevoke: "本当に失効する",
  },
  changePassword: {
    lead: "初期パスワードから変更してください。",
    tooShort: "新しいパスワードは10文字以上にしてください。",
    failed: "変更に失敗しました。現在のパスワードを確認してください。",
    current: "現在のパスワード",
    next: "新しいパスワード（10文字以上）",
    done: "パスワードを変更しました。",
    submit: "変更する →",
  },
  members: {
    title: "メンバー",
    inviteLead: "名前とメールアドレスを入れると招待メールが届きます。相手がリンクからパスワードを設定すれば、ログインと Claude（MCP）接続ができます。どのドメインのメールでも招待できます。",
    name: "名前",
    email: "メールアドレス",
    role: "権限",
    roleMember: "メンバー",
    roleAdmin: "管理者",
    invite: "招待メールを送る →",
    listFailed: "メンバー一覧の取得に失敗しました。",
    inviteFailed: "招待に失敗しました。",
    invited: (email: string) => `${email} に招待メールを送りました。届いたリンクからパスワードを設定するとログインできます。`,
    reinvited: (email: string) => `${email} は登録済みのため、招待メールを再送しました。`,
    resendFailed: "招待メールの再送に失敗しました。",
    resent: (email: string) => `${email} に招待メールを再送しました（リンクは7日間有効）。`,
    roleFailed: "権限の変更に失敗しました。",
    removeFailed: "削除に失敗しました。",
    tooShort: "新しいパスワードは10文字以上にしてください。",
    resetFailed: "パスワードの再設定に失敗しました。",
    resetDone: "パスワードを再設定しました。本人に新しいパスワードを渡してください。",
    self: "（自分）",
    added: (date: string) => `追加 ${date}`,
    newPassword: "新しいパスワード",
    set: "設定",
    resend: "招待メールを再送",
    setPassword: "パスワードを直接設定",
    makeMember: "メンバーにする",
    makeAdmin: "管理者にする",
    cannotRemoveSelf: "自分自身は削除できません。",
    apiErrors: {
      invalid_email: "有効なメールアドレスを入力してください。",
      name_required: "名前を入力してください。",
      send_failed: "招待メールの送信に失敗しました。RESEND の設定を確認してください。",
    } as Record<string, string>,
  },
  login: {
    title: "メンバー認証",
    failed: "認証に失敗しました。",
    submitting: "認証中…",
    submit: "サインイン →",
    forgot: "パスワードをお忘れですか？",
    noticeInvite: "パスワードを設定しました。招待メールのアドレスでログインしてください。",
    noticeReset: "パスワードを再設定しました。新しいパスワードでログインしてください。",
  },
  forgot: {
    title: "パスワードをお忘れですか？",
    sent: "登録済みのアドレスであれば、再設定用のリンクを送りました。届かない場合は迷惑メールフォルダも確認してください。",
    email: "登録しているメールアドレス",
    failed: "送信に失敗しました。しばらくしてからもう一度お試しください。",
    sending: "送信中…",
    submit: "再設定メールを送る →",
    back: "← ログインへ戻る",
  },
  setPassword: {
    titleInvite: "パスワードを設定",
    titleReset: "パスワードを再設定",
    invalid: "リンクが無効か、有効期限が切れています。",
    askAdmin: "管理者に招待メールの再送を依頼してください。",
    resendBefore: "",
    resendLink: "こちら",
    resendAfter: "から再設定メールを送り直せます。",
    welcome: "Bakerization Research へようこそ。ログイン用のパスワードを決めてください。設定後、招待メールのアドレスでログインできます。",
    next: "新しいパスワード（10文字以上）",
    confirm: "もう一度入力",
    tooShort: "パスワードは10文字以上にしてください。",
    mismatch: "確認用のパスワードが一致しません。",
    failed: "設定に失敗しました。リンクの有効期限が切れている可能性があります。",
    setting: "設定中…",
    submitInvite: "設定してはじめる →",
    submitReset: "再設定する →",
  },
  consent: {
    title: "接続を許可しますか？",
    permissions: "許可する内容",
    failed: "処理に失敗しました。もう一度やり直してください。",
    processing: "処理中…",
    allow: "許可する →",
    deny: "拒否",
    scopes: {
      research: "Research のプロジェクト閲覧とアーティファクトの公開・更新",
      openid: "ログイン状態の確認",
      profile: "表示名の参照",
      email: "メールアドレスの参照",
      offline_access: "接続を維持（トークンの自動更新）",
    } as Record<string, string>,
  },
  meta: {
    indexDescription: "Bakerization が調査・分析したリサーチを公開しています。パン屋と食、テクノロジーに関するレポートをプロジェクトごとに閲覧できます。",
    projectDescription: (name: string) => `${name} — Bakerization Research のプロジェクト`,
    artifactDescription: (title: string) => `${title} — Bakerization Research`,
    login: "メンバー認証",
    forgot: "パスワード再設定",
    invite: "パスワードを設定",
    reset: "パスワード再設定",
    consent: "接続の許可",
  },
};

export type ResearchCopy = typeof ja;

const en: ResearchCopy = {
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    closeX: "Close ✕",
    delete: "Delete",
    confirmDelete: "Really delete",
    copy: "Copy",
    copied: "Copied",
    required: "Required",
    loading: "Loading…",
    descriptionOptional: "Description (optional)",
    description: "Description",
    title: "Title",
  },
  visibility: {
    label: "Visibility",
    publicTitle: "Anyone can view (no sign-in, indexed by search engines)",
    membersTitle: "Members only",
    membersOption: "Members only",
    publicOption: "Anyone (indexed by search)",
    makePublic: "Make public",
    makeMembers: "Members only",
    changeFailed: "Couldn't change visibility.",
  },
  header: {
    projects: "Projects",
    settings: "Settings",
    members: "Members",
    logout: "Sign out",
    menu: "Menu",
  },
  index: {
    title: "Projects",
    lead: "HTML artifacts made with Claude, organized by project. See Settings for how to publish from Cowork / Claude.",
    empty: "No projects yet. Create one with “New project”.",
    count: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
    updated: (date: string) => `Updated ${date}`,
  },
  publicIndex: {
    title: "Research",
    lead: "Reports and analyses published by Bakerization — research on bakeries, food and technology, organized by project.",
    projects: "Projects",
    latest: "Latest research",
    empty: "No published research yet.",
    reports: (n: number) => `${n} ${n === 1 ? "report" : "reports"}`,
    updated: (date: string) => `Updated ${date}`,
    open: "Read →",
  },
  publicProject: {
    back: "← All research",
    reports: (n: number) => `${n} ${n === 1 ? "report" : "reports"}`,
  },
  newProject: {
    open: "+ New project",
    name: "Project name",
    creating: "Creating…",
    create: "Create →",
    failed: "Couldn't create the project.",
  },
  board: {
    viewToggle: "View",
    list: "List",
    grid: "Grid",
    projectSettings: "Project settings",
    upload: "+ Upload",
    name: "Project name",
    deleteProject: "Delete project",
    confirmDeleteProject: "Really delete (items move to Inbox)",
    empty: "No artifacts yet. Add one with “Upload”, or from Claude (MCP connector) / the API.",
    dragHint: "Drag ⋮⋮ to reorder (keyboard: focus the handle → Space → arrows → Space)",
    colPreview: "Preview",
    colMeta: "Title · Source · Author · Updated",
    colActions: "Actions",
    reorderFailed: "Couldn't save the new order. Restored the previous order.",
    updateFailed: "Couldn't update the project.",
    deleteFailed: "Couldn't delete the project.",
  },
  item: {
    dragHandle: "Reorder (drag, or Space → arrow keys → Space)",
    open: "Open",
    rename: "Rename",
    move: "Move",
    moveTo: "Move to…",
    updateFailed: "Couldn't save.",
    moveFailed: "Couldn't move.",
    deleteFailed: "Couldn't delete.",
  },
  upload: {
    title: "Upload HTML",
    onlyHtml: "Only .html files are supported.",
    tooLarge: (limit: string) => `File is too large (max ${limit}).`,
    empty: "The HTML is empty.",
    failed: "Upload failed.",
    selected: (name: string) => `Selected: ${name}`,
    drop: "Choose a file, or drop it here (.html)",
    paste: "Or paste HTML",
    uploading: "Uploading…",
    submit: "Upload →",
  },
  viewer: {
    backTo: (name: string) => `Back to ${name}`,
    backHome: "All research",
    descriptionPlaceholder: "Add a description…",
    details: "Details and actions",
    rename: "Rename",
    openHtml: "Open HTML ↗",
    download: "Download",
    copyUrl: "Copy URL",
    saveFailed: "Couldn't save.",
    deleteFailed: "Couldn't delete.",
  },
  settings: {
    title: "Settings",
  },
  apiKeys: {
    lead: "Keys for the REST API (curl / Claude Code scripts). A key is shown only once, when it's created.",
    fetchFailed: "Couldn't load keys.",
    createFailed: "Couldn't create the key.",
    revokeFailed: "Couldn't revoke the key.",
    revealWarning: "▲ This key won't be shown again. Copy it now and store it somewhere safe.",
    name: "Key name (e.g. Claude Code / automation script)",
    issue: "Create →",
    none: "No keys yet.",
    created: (date: string) => `Created ${date}`,
    lastUsed: (date: string) => `Last used ${date}`,
    unused: "Never used",
    revoke: "Revoke",
    confirmRevoke: "Really revoke",
  },
  changePassword: {
    lead: "Replace your initial password.",
    tooShort: "The new password must be at least 10 characters.",
    failed: "Couldn't change the password. Check your current password.",
    current: "Current password",
    next: "New password (10+ characters)",
    done: "Password changed.",
    submit: "Change →",
  },
  members: {
    title: "Members",
    inviteLead: "Enter a name and email to send an invitation. Once they set a password from the link, they can sign in and connect Claude (MCP). Any email domain works.",
    name: "Name",
    email: "Email",
    role: "Role",
    roleMember: "Member",
    roleAdmin: "Admin",
    invite: "Send invitation →",
    listFailed: "Couldn't load members.",
    inviteFailed: "Couldn't send the invitation.",
    invited: (email: string) => `Invitation sent to ${email}. They can sign in after setting a password from the link.`,
    reinvited: (email: string) => `${email} is already registered, so the invitation was sent again.`,
    resendFailed: "Couldn't resend the invitation.",
    resent: (email: string) => `Invitation resent to ${email} (the link is valid for 7 days).`,
    roleFailed: "Couldn't change the role.",
    removeFailed: "Couldn't delete.",
    tooShort: "The new password must be at least 10 characters.",
    resetFailed: "Couldn't reset the password.",
    resetDone: "Password reset. Give the new password to the member.",
    self: "(you)",
    added: (date: string) => `Added ${date}`,
    newPassword: "New password",
    set: "Set",
    resend: "Resend invitation",
    setPassword: "Set password directly",
    makeMember: "Make member",
    makeAdmin: "Make admin",
    cannotRemoveSelf: "You can't delete yourself.",
    apiErrors: {
      invalid_email: "Enter a valid email address.",
      name_required: "Enter a name.",
      send_failed: "Couldn't send the invitation email. Check the RESEND settings.",
    },
  },
  login: {
    title: "Member sign-in",
    failed: "Sign-in failed.",
    submitting: "Signing in…",
    submit: "Sign in →",
    forgot: "Forgot your password?",
    noticeInvite: "Your password is set. Sign in with the address the invitation was sent to.",
    noticeReset: "Your password was reset. Sign in with the new password.",
  },
  forgot: {
    title: "Forgot your password?",
    sent: "If that address is registered, we've sent a reset link. Check your spam folder if it doesn't arrive.",
    email: "Your registered email",
    failed: "Couldn't send. Please try again in a moment.",
    sending: "Sending…",
    submit: "Send reset email →",
    back: "← Back to sign-in",
  },
  setPassword: {
    titleInvite: "Set your password",
    titleReset: "Reset your password",
    invalid: "This link is invalid or has expired.",
    askAdmin: "Ask an admin to resend the invitation.",
    resendBefore: "You can ",
    resendLink: "request a new reset email",
    resendAfter: ".",
    welcome: "Welcome to Bakerization Research. Choose a password; you'll then sign in with the address the invitation was sent to.",
    next: "New password (10+ characters)",
    confirm: "Enter it again",
    tooShort: "The password must be at least 10 characters.",
    mismatch: "The passwords don't match.",
    failed: "Couldn't set the password. The link may have expired.",
    setting: "Saving…",
    submitInvite: "Set and get started →",
    submitReset: "Reset →",
  },
  consent: {
    title: "Allow this connection?",
    permissions: "This will allow",
    failed: "Something went wrong. Please try again.",
    processing: "Working…",
    allow: "Allow →",
    deny: "Deny",
    scopes: {
      research: "View Research projects and publish / update artifacts",
      openid: "Confirm that you're signed in",
      profile: "Read your display name",
      email: "Read your email address",
      offline_access: "Stay connected (refresh tokens automatically)",
    },
  },
  meta: {
    indexDescription: "Research published by Bakerization — reports on bakeries, food and technology, organized by project.",
    projectDescription: (name: string) => `${name} — a Bakerization Research project`,
    artifactDescription: (title: string) => `${title} — Bakerization Research`,
    login: "Member sign-in",
    forgot: "Reset password",
    invite: "Set your password",
    reset: "Reset password",
    consent: "Allow connection",
  },
};

export const RESEARCH_COPY: Record<Locale, ResearchCopy> = { ja, en };

export function getResearchCopy(locale: Locale): ResearchCopy {
  return RESEARCH_COPY[locale];
}
